// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnlosxmzbzesyubocgmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhubG9zeG16Ynplc3l1Ym9jZ21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDgyMzcsImV4cCI6MjA2OTM4NDIzN30.kN3mNhTcbqt6xx8viC3uUYOnG_5V8r8giIKundO1A2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});